### PR TITLE
fix(ui): Show correct oldest result timestamp

### LINKED ISSUE #1404: Incorrect oldest result time in home view
### Describe the bug

Is is possible for the oldest result timestamp of the EndpointCard component to be incorrect as it is currently used in the home view.

### What do you see?

For an endpoint interval of 1m the timestamp will shows  "2 hours ago" even tough the last visible timestamp is only from ~50min ago.

Image

Image

### What do you expect to see?

Timestamp displaying "50 minutes ago" like in the EndpointDetails view:

Image

### List the steps that must be taken to reproduce this issue

1. Create endpoint with short interval
2. Wait for result list to fill up and then a little longer

### Version

v5.33.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by PythonGermany**
## Summary

Closes #1404

## Checklist

- [x] (n/a) Tested and/or added tests to validate that the changes work as intended, if applicable.
- [x] (n/a) Updated documentation in `README.md`, if applicable.

### CODE REVIEW

**Comment by PythonGermany** [comment]
Are there any relevant UI tests that I can extend with a check to verify that the timestamps match the displayed result range?

**Comment by TwiN** [comment]
@PythonGermany I'm not a fan of frontend tests to be honest, so feel free to skip testing the frontend changes. I do most of my frontend tests manually, though I'm having an issue replicating your issue on my end.

**Comment by PythonGermany** [comment]
The issue can also be observed in the [demo](https://status.twin.sh/). In the EndpointCard component of the blog-external endpoint of the home view it says something like "2 hours ago" for oldest result and "31 seconds ago" for latest result. However if you then look at the timestamp of the first and last displayed result in the green status bar above the oldest displayed result is about ~50 minutes ago. This issue does not occur on the [details page ](https://status.twin.sh/endpoints/core_blog-external) of the endpoint. There the oldest result timestamp is displayed correctly.

File: web/app/src/views/Home.vue [hunk 1]
```diff
@@ -433,7 +434,7 @@ const fetchData = async () => {
   }
   try {
     // Fetch endpoints
-    const endpointResponse = await fetch(`${SERVER_URL}/api/v1/endpoints/statuses?page=1&pageSize=100`, {
+    const endpointResponse = await fetch(`${SERVER_URL}/api/v1/endpoints/statuses?page=1&pageSize=${resultPageSize}`, {
```
Comment (TwiN) [inline web/app/src/views/Home.vue:437]: I think this may have been the issue honestly. Good catch; looks like some bugs fell through the cracks when I updated the UI

Comment (PythonGermany) [reply web/app/src/views/Home.vue:437]: Yes, this issue and the one in the EndpointCard component combined caused the UI bug. Each on their own wouldn't have caused any UI issues.

**Comment by TwiN** [comment]
Thank you for the contribution @PythonGermany !
