### PR TITLE
fix(security): Do not allow invalid security configs

### LINKED ISSUE #1530: Invalid security config allowed during startup
As I discovered and first mentioned here: https://github.com/TwiN/gatus/pull/1350#discussion_r2756344229:

> If more than one auth method is configured and the config for at least one of them is valid the validation check result for all other config sections is disregarded.
> 
> In such cases Gatus will still start without any indication of an invalid config even though it should show an error and quit immediately.

### PR DESCRIPTION
**Pull request by PythonGermany**
## Summary

Closes #1530 

## Checklist

- [x] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [x] (n/a) Updated documentation in `README.md`, if applicable.

### CODE REVIEW

File: security/config.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ type Config struct {
 
 // ValidateAndSetDefaults returns whether the security configuration is valid or not and sets default values.
 func (c *Config) ValidateAndSetDefaults() bool {
-	return (c.Basic != nil && c.Basic.isValid()) || (c.OIDC != nil && c.OIDC.ValidateAndSetDefaults())
+	return (c.Basic == nil || c.Basic.isValid()) && (c.OIDC == nil || c.OIDC.ValidateAndSetDefaults())
```
Comment (TwiN) [inline security/config.go:31]: Can you add a comment? It's not super clear what we're trying to achieve here

**Review by TwiN — CHANGES_REQUESTED** [review]

File: security/config.go (hunk 1 above)
Comment (TwiN) [reply security/config.go:31]: Nevermind, makes sense

**Review by TwiN — APPROVED** [review]
