### PR TITLE
fix: handle HTTP header names case-insensitively

### LINKED ISSUE #1491: HTTP header names should be case insensitive
### Describe the bug

where we configure headers like this:

```
endpoints:
  - headers:
      user-agent: Mozilla/5.0
```

due to how gatus is coded and maps in golang work, it's a toss up will we get mozilla or gatus header effectively applied to request, so results are random. Can we fix this so that the header names are truly case insensitive as they should be?

### What do you see?

endpoints fail intermittently due to wrong header sent

### What do you expect to see?

the header is sent as specified in configuration without another header of the same name being sent by gatus itself

### List the steps that must be taken to reproduce this issue

1. use the headers config similar to above
2. observe on the server polled that headers received are mixed

### Version

5.34.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AnuragEkkati**
Details: HTTP header names should be case-insensitive per RFC 7230. When the users configure the headers like 'user-agent' (lowercase), gatus was adding its own 'User-Agent' header because the case-sensitive map lookup failed to find the existing header.

Fixed headers:
- User-Agent
- Content-Type
- Host

Fixes #1491

## Checklist

- [X] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [ ] Updated documentation in `README.md`, if applicable.

### CODE REVIEW

File: config/endpoint/endpoint.go [hunk 1]
```diff
@@ -189,6 +189,16 @@ func (e *Endpoint) Type() Type {
 	}
 }
 
+// hasHeader checks if a header exists in the map using a case-insensitive lookup
+func hasHeader(headers map[string]string, name string) bool {
```
Comment (TwiN) [inline config/endpoint/endpoint.go]: Can you move this function at the bottom of the file?

Comment (AnuragEkkati) [reply config/endpoint/endpoint.go]: Sure. Will update it now. 

Thanks for the review

Comment (AnuragEkkati) [reply config/endpoint/endpoint.go]: Done.

**Comment by TwiN** [comment]
Thank you for the contribution!
