### PR TITLE
fix(watchdog): Close dangling file descriptors on shutdown and config reload

### LINKED ISSUE #536: Gatus leaves dangling open file descriptors after reloading configuration
### Describe the bug

We noticed a weird behavior in Gatus that led to a horde of false negatives, all with the failure message related to too many open files. Curiously this happened to only a few endpoints.

After poking around, I found out that Gatus leaves open file descriptors and create new ones when re-reading the configuration files.

### What do you see?

_No response_

### What do you expect to see?

Gatus should close file descriptors instead of leaving them open after a reload.

### List the steps that must be taken to reproduce this issue

1. Add an sqlite database to the default configuration file, e.g.:
   ```yaml
   storage:
     type: sqlite
     path: /tmp/data.db
   ```
1. Start Gatus directly, i.e. `./gatus`
1. Open another terminal and list all open files from Gatus, e.g. with `watch`: 
   ```bash
   $ watch -d -n .5 --color ls -lah --color /proc/`ps aux | grep './gatus' | head -n 1 | awk '{print $2}'`/fd
   ```

At this point you should have Gatus running on one terminal and another one showing all open file descriptors from Gatus. With the default configuration file + an sqlite DB I see 10 open fd:

```
lrwx------ 1 h users 64 jul 25 15:43 0 -> /dev/pts/3
lrwx------ 1 h users 64 jul 25 15:43 1 -> /dev/pts/3
lrwx------ 1 h users 64 jul 25 15:43 10 -> socket:[58680]
lrwx------ 1 h users 64 jul 25 15:43 2 -> /dev/pts/3
lrwx------ 1 h users 64 jul 25 15:43 3 -> /tmp/data.db
lrwx------ 1 h users 64 jul 25 15:43 4 -> anon_inode:[eventpoll]
lr-x------ 1 h users 64 jul 25 15:43 5 -> pipe:[53621]
l-wx------ 1 h users 64 jul 25 15:43 6 -> pipe:[53621]
lrwx------ 1 h users 64 jul 25 15:43 7 -> /tmp/data.db-wal
lrwx------ 1 h users 64 jul 25 15:43 8 -> /tmp/data.db-shm
lrwx------ 1 h users 64 jul 25 15:43 9 -> socket:[53627]
```

Now trigger a reload of the config files by renaming any endpoint in the `config.yaml`, wait for gatus to reload and check the number of open files. We should have the same number of fds, but there are more:

```
dr-x------ 2 h users  0 jul 25 15:43 .
dr-xr-xr-x 9 h users  0 jul 25 15:42 ..
lrwx------ 1 h users 64 jul 25 15:43 0 -> /dev/pts/3
lrwx------ 1 h users 64 jul 25 15:43 1 -> /dev/pts/3
lrwx------ 1 h users 64 jul 25 15:43 10 -> socket:[58680]
lrwx------ 1 h users 64 jul 25 15:47 11 -> /tmp/data.db-wal
lrwx------ 1 h users 64 jul 25 15:49 12 -> socket:[80202]
lrwx------ 1 h users 64 jul 25 15:50 13 -> socket:[80206]
lrwx------ 1 h users 64 jul 25 15:43 2 -> /dev/pts/3
lrwx------ 1 h users 64 jul 25 15:43 3 -> /tmp/data.db
lrwx------ 1 h users 64 jul 25 15:43 4 -> anon_inode:[eventpoll]
lr-x------ 1 h users 64 jul 25 15:43 5 -> pipe:[53621]
l-wx------ 1 h users 64 jul 25 15:43 6 -> pipe:[53621]
lrwx------ 1 h users 64 jul 25 15:43 7 -> /tmp/data.db-wal
lrwx------ 1 h users 64 jul 25 15:43 8 -> /tmp/data.db-shm
lrwx------ 1 h users 64 jul 25 15:43 9 -> /tmp/data.db
```

Renaming more endpoints increase the number of open fds even more.

Summary:
- every time the configuration is reloaded, gatus reopen the DB file, leaving the other file descriptors open. In the example above you can see `/tmp/data.db` listed twice. Reload the configuration again and you will see it 3 times.
- Something similar happens to the sockets, they are not closed before a reload.

### Version

Latest commit from `master` branch: 162dd9bc

### Additional information

Gatus compiled with:

```bash
$ go version
go version go1.20.4 linux/amd64

$ CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gatus .
```

### PR DESCRIPTION
**Pull request by vax-r**
## Summary
This PR adds feature to close storage and socket connections when stopping the service
especially when reloading config.yaml file

Fixes #536 

## Checklist

- [X] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [X] Updated documentation in `README.md`, if applicable.

### CODE REVIEW

File: core/endpoint.go [hunk 1]
```diff
@@ -364,6 +364,12 @@ func (endpoint *Endpoint) call(result *Result) {
 	}
 }
 
+func (endpoint *Endpoint) CloseHTTPConnection() {
+	if endpoint.Type() == EndpointTypeHTTP {
+		client.GetHTTPClient(endpoint.ClientConfig).CloseIdleConnections()
+	}
+}
```
Comment (TwiN) [inline core/endpoint.go:371]: Should this perhaps be renamed to `Close()` just in case there are other endpoints types that need something to be closed as well in the future?

Also, perhaps a comment above that function would be useful -- I'd include a reference to the issue: `https://github.com/TwiN/gatus/issues/536`

**Review by TwiN — CHANGES_REQUESTED** [review]

File: core/endpoint.go (hunk 1 above)
Comment (vax-r) [reply core/endpoint.go:371]: No problem!
I'll modify it quickly and commit it.
I'll ask for your review by then, thank you!

File: core/endpoint.go [hunk 2]
```diff
@@ -364,6 +364,18 @@ func (endpoint *Endpoint) call(result *Result) {
 	}
 }
 
+/*
+This function is using to close HTTP connection between watchdog and endpoints
```
[the remark this answers is not in the document]
Comment (TwiN) [reply core/endpoint.go:368]: N/A because I'm going to rewrite the comment completely

File: core/endpoint.go [hunk 3]
```diff
@@ -364,6 +364,18 @@ func (endpoint *Endpoint) call(result *Result) {
...
+So we can avoid dangling socket file descriptors
+If we find similar issue to this in the future, we can add the disconnection method in this function
+Reference: https://github.com/TwiN/gatus/issues/536
+*/
+func (endpoint *Endpoint) Close() {
```
Comment (TwiN) [inline core/endpoint.go:373]:
```suggestion
// Close closes HTTP connections between watchdog and endpoints to avoid dangling socket file descriptors
// on configuration reload.
// More context on https://github.com/TwiN/gatus/issues/536
func (endpoint *Endpoint) Close() {
```

File: core/endpoint.go [hunk 4]
```diff
@@ -364,6 +364,15 @@ func (endpoint *Endpoint) call(result *Result) {
 	}
 }
 
+// Close closes HTTP connections between watchdog and endpoints to avoid dangling socket file descriptors
```
Comment (TwiN) [inline core/endpoint.go:367]:
```suggestion
// Close HTTP connections between watchdog and endpoints to avoid dangling socket file descriptors
```

**Review by TwiN — APPROVED** [review]

**Comment by TwiN** [comment]
Thank you for the contribution!
